name: Compiling LaTeX

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          image: ghcr.io/cpp-review-dune/introductory-review/texlive:latest
          options: -v ${{github.workspace}}:/work
          shell: bash
          run: |
            cd /work/primera && arara primera.tex

      - name: "Tar files"
        run: |
          tar --zstd -cf PDF.tar.zst primera/*.pdf

      - uses: actions/upload-artifact@v2
        with:
          name: PDF-artifact
          path: PDF.tar.zst
          if-no-files-found: error
          retention-days: 5
