name: Deploy pages

on:
  push:
    branches:
      - main

jobs:
  deploy_pages:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: compile.yml
          name: PDF-primera-artifact

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: compile.yml
          name: PDF-segunda-artifact

      - name: "Untar files"
        run: |
          tar -I zstd -xvf PDF-primera.tar.zst
          mv primera/*.pdf docs
          tar -I zstd -xvf PDF-segunda.tar.zst
          mv segunda/*.pdf docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
